language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "Kj6s9yXqOiXyJobgdz+duPw6QEuoTbIG8co33EFny+v7Ot8+3wFTkLtqxM4Y7T0iKP4hKHyVsaPXxOoTI1cQhySJwvd/4krkD/d2o/Mk4RwhEq+VMU38B12J+NVz7441C6aQwnkC0KI8iysfxsOL/K4t67O7YvmiWjKKr5TaNgU="1